- hosts: taskA
  tasks:
  - name: Install the latest version of Apache
    apt:
      name: apache2
      state: latest

  - name: Make sure a service is running
    systemd:
      name: apache2
      state: started
      enabled: yes

  - name: Install unzip
    apt:
      name: unzip
      state: latest

  - name: Download  and extract template below
    unarchive:
      src: https://www.free-css.com/assets/files/free-css-templates/download/page287/cycle.zip
      dest: /var/www/
      remote_src: yes

  